export default {
  colors: {
    text: "#000",
    testText: "#262627",
    backgroundGrey: "#F2F2F2",
    transparentBackgroundGrey: "rgba(242, 242, 242, .6)",
    testBackgroundGrey: "#f1ece4",
    background: "#fff",
    white: "#fff",
    primary: "#DB2721",
    secondary: "#69A1AC",
    highlight: "#FF4133",
    secondaryLight: "#89C5CC",
    muted: "#828282",
    purp: "#925CAB",
  },
  shadows: {
    primary: "0px 4px 10px #CECECE",
    primaryHover: "0px 4px 15px rgba(105, 161, 172, 0.44)",
  },
  radii: {
    primary: "10px",
    secondary: "25px",
  },
  borders: {
    primary: "2px solid #DB2721",
    secondary: "2px solid #89C5CC",
  },
  fonts: {
    body: "Ubuntu, Open Sans, Segoe UI, sans-serif",
    heading: "Merriweather, serif",
    monospace: "Menlo, monospace",
  },
  fontWeights: {
    light: 300,
    body: 400,
    heading: 700,
    bold: 700,
    heavy: 900,
    semibold: 500,
  },
  lineHeights: {
    body: 2,
    heading: 1.125,
  },
  sizes: {
    landingCardContainer: 600,
    blogPreviewCard: 500,
    blogListCard: 600,
    blogPost: 800,
    serviceCard: ["150px", "300px"],
  },
  fontSizes: [12, 14, 16, 18, 20, 24, 30, 36, 48, 60, 72],
  space: [0, 4, 8, 12, 16, 24, 32, 48, 64, 96, 128, 256, 512],
  breakpoints: ["40em", "56em", "64em"],
  buttons: {
    primary: {
      color: "white",
      bg: "primary",
      px: [5, 6],
      py: [0],
      border: "primary",
      borderRadius: "primary",
      whiteSpace: "nowrap",
      "&:hover": {
        cursor: "pointer",
      },
    },
    secondary: {
      color: "primary",
      bg: "white",
      px: [2, 3, 4],
      py: [1],
      border: "primary",
      borderRadius: "primary",
      whiteSpace: "nowrap",
      transition: "filter 400ms",
      "&:not(:disabled):hover": {
        cursor: "pointer",
        filter: "contrast(175%) drop-shadow(0px 5px 10px #f2f2f2)",
      },
    },
  },
  cards: {
    blogPreview: {
      bg: "backgroundGrey",
      borderRadius: "primary",
      display: "flex",
      flexDirection: "column",
      justifyContent: "left",
      padding: 3,
      margin: 2,
      filter: "drop-shadow(16px 16px 20px #F2F2F2)",
    },
    blogListCard: {
      bg: "white",
      maxWidth: "blogListCard",
      borderRadius: "primary",
      display: "flex",
      flexDirection: "column",
      justifyContent: "left",
      padding: [3, 6],
      filter: "drop-shadow(16px 16px 20px #CECECE)",
    },
    blogPost: {
      bg: "white",
      maxWidth: "blogPost",
      marginX: "auto",
      marginTop: "2rem",
      borderRadius: "primary",
      display: "flex",
      flexDirection: "column",
      justifyContent: "left",
      padding: [3, 6],
      filter: "drop-shadow(16px 16px 20px #CECECE)",
    },
  },
  inputs: {
    newsletter: {
      border: "none",
      borderRadius: "10px 0 0 10px",
      bg: "white",
      padding: 2,
    },
    primary: {
      border: "none",
      borderRadius: "10px",
      bg: "white",
      padding: 2,
    },
  },
  text: {
    heading: {
      fontFamily: "heading",
      lineHeight: "heading",
      fontWeight: "heading",
    },
  },
  styles: {
    root: {
      fontFamily: "body",
      lineHeight: "body",
      fontWeight: "body",
    },
    h1: {
      variant: "text.heading",
      fontSize: 9,
    },
    h2: {
      variant: "text.heading",
      fontSize: [6, 7, 8],
    },
    h3: {
      variant: "text.heading",
      fontSize: [5, 6, 7],
    },
    h4: {
      variant: "text.heading",
      fontSize: [3, 4, 5],
    },
    h5: {
      variant: "text.heading",
      fontSize: [2, 3, 4],
    },
    h6: {
      variant: "text.heading",
      fontSize: 1,
    },
  },
}
